/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LogSentinel.Client.Client;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing LogSpecialApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LogSpecialApiTests
    {
        private LogSpecialApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LogSpecialApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogSpecialApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LogSpecialApi
            //Assert.IsInstanceOfType(typeof(LogSpecialApi), instance, "instance is a LogSpecialApi");
        }

        
        /// <summary>
        /// Test LogProvenance
        /// </summary>
        [Test]
        public void LogProvenanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string applicationId = null;
            //string provenanceDocument = null;
            //var response = instance.LogProvenance(applicationId, provenanceDocument);
            //Assert.IsInstanceOf<LogResponse> (response, "response is LogResponse");
        }
        
    }

}
