/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using LogSentinel.Client.Client;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing SavedSearchesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SavedSearchesApiTests
    {
        private SavedSearchesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SavedSearchesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SavedSearchesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SavedSearchesApi
            //Assert.IsInstanceOfType(typeof(SavedSearchesApi), instance, "instance is a SavedSearchesApi");
        }

        
        /// <summary>
        /// Test CreateSavedSearch
        /// </summary>
        [Test]
        public void CreateSavedSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? end = null;
            //string name = null;
            //int? page = null;
            //int? pageSize = null;
            //string query = null;
            //long? start = null;
            //var response = instance.CreateSavedSearch(end, name, page, pageSize, query, start);
            //Assert.IsInstanceOf<List<SavedSearch>> (response, "response is List<SavedSearch>");
        }
        
        /// <summary>
        /// Test GetSavedSearchIds
        /// </summary>
        [Test]
        public void GetSavedSearchIdsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSavedSearchIds();
            //Assert.IsInstanceOf<List<SavedSearch>> (response, "response is List<SavedSearch>");
        }
        
        /// <summary>
        /// Test PerformSavedSearch
        /// </summary>
        [Test]
        public void PerformSavedSearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string savedSearchId = null;
            //var response = instance.PerformSavedSearch(savedSearchId);
            //Assert.IsInstanceOf<List<AuditLogEntry>> (response, "response is List<AuditLogEntry>");
        }
        
    }

}
