/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing AlertRuleRun
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertRuleRunTests
    {
        // TODO uncomment below to declare an instance variable for AlertRuleRun
        //private AlertRuleRun instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertRuleRun
            //instance = new AlertRuleRun();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertRuleRun
        /// </summary>
        [Test]
        public void AlertRuleRunInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertRuleRun
            //Assert.IsInstanceOfType<AlertRuleRun> (instance, "variable 'instance' is a AlertRuleRun");
        }


        /// <summary>
        /// Test the property 'ActualValue'
        /// </summary>
        [Test]
        public void ActualValueTest()
        {
            // TODO unit test for the property 'ActualValue'
        }
        /// <summary>
        /// Test the property 'AlertRuleId'
        /// </summary>
        [Test]
        public void AlertRuleIdTest()
        {
            // TODO unit test for the property 'AlertRuleId'
        }
        /// <summary>
        /// Test the property 'AlertRuleName'
        /// </summary>
        [Test]
        public void AlertRuleNameTest()
        {
            // TODO unit test for the property 'AlertRuleName'
        }
        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Test]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Test]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }
        /// <summary>
        /// Test the property 'ExecutionDuration'
        /// </summary>
        [Test]
        public void ExecutionDurationTest()
        {
            // TODO unit test for the property 'ExecutionDuration'
        }
        /// <summary>
        /// Test the property 'Fired'
        /// </summary>
        [Test]
        public void FiredTest()
        {
            // TODO unit test for the property 'Fired'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Test]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'Threshold'
        /// </summary>
        [Test]
        public void ThresholdTest()
        {
            // TODO unit test for the property 'Threshold'
        }
        /// <summary>
        /// Test the property 'ThresholdType'
        /// </summary>
        [Test]
        public void ThresholdTypeTest()
        {
            // TODO unit test for the property 'ThresholdType'
        }

    }

}
