/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing AlertRuleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertRuleRequestTests
    {
        // TODO uncomment below to declare an instance variable for AlertRuleRequest
        //private AlertRuleRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertRuleRequest
            //instance = new AlertRuleRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertRuleRequest
        /// </summary>
        [Test]
        public void AlertRuleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertRuleRequest
            //Assert.IsInstanceOfType<AlertRuleRequest> (instance, "variable 'instance' is a AlertRuleRequest");
        }


        /// <summary>
        /// Test the property 'AggregationPeriod'
        /// </summary>
        [Test]
        public void AggregationPeriodTest()
        {
            // TODO unit test for the property 'AggregationPeriod'
        }
        /// <summary>
        /// Test the property 'AggregationType'
        /// </summary>
        [Test]
        public void AggregationTypeTest()
        {
            // TODO unit test for the property 'AggregationType'
        }
        /// <summary>
        /// Test the property 'AlertDestinationIds'
        /// </summary>
        [Test]
        public void AlertDestinationIdsTest()
        {
            // TODO unit test for the property 'AlertDestinationIds'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'GroupByField'
        /// </summary>
        [Test]
        public void GroupByFieldTest()
        {
            // TODO unit test for the property 'GroupByField'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SearchPeriod'
        /// </summary>
        [Test]
        public void SearchPeriodTest()
        {
            // TODO unit test for the property 'SearchPeriod'
        }
        /// <summary>
        /// Test the property 'ThresholdValue'
        /// </summary>
        [Test]
        public void ThresholdValueTest()
        {
            // TODO unit test for the property 'ThresholdValue'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
