/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing BatchLogRequestEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchLogRequestEntryTests
    {
        // TODO uncomment below to declare an instance variable for BatchLogRequestEntry
        //private BatchLogRequestEntry instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchLogRequestEntry
            //instance = new BatchLogRequestEntry();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchLogRequestEntry
        /// </summary>
        [Test]
        public void BatchLogRequestEntryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchLogRequestEntry
            //Assert.IsInstanceOfType<BatchLogRequestEntry> (instance, "variable 'instance' is a BatchLogRequestEntry");
        }


        /// <summary>
        /// Test the property 'ActionData'
        /// </summary>
        [Test]
        public void ActionDataTest()
        {
            // TODO unit test for the property 'ActionData'
        }
        /// <summary>
        /// Test the property 'ActorData'
        /// </summary>
        [Test]
        public void ActorDataTest()
        {
            // TODO unit test for the property 'ActorData'
        }
        /// <summary>
        /// Test the property 'AdditionalParams'
        /// </summary>
        [Test]
        public void AdditionalParamsTest()
        {
            // TODO unit test for the property 'AdditionalParams'
        }
        /// <summary>
        /// Test the property 'BinaryContent'
        /// </summary>
        [Test]
        public void BinaryContentTest()
        {
            // TODO unit test for the property 'BinaryContent'
        }
        /// <summary>
        /// Test the property 'EncryptedKeywordsList'
        /// </summary>
        [Test]
        public void EncryptedKeywordsListTest()
        {
            // TODO unit test for the property 'EncryptedKeywordsList'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
