/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing EthereumData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EthereumDataTests
    {
        // TODO uncomment below to declare an instance variable for EthereumData
        //private EthereumData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EthereumData
            //instance = new EthereumData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EthereumData
        /// </summary>
        [Test]
        public void EthereumDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EthereumData
            //Assert.IsInstanceOfType<EthereumData> (instance, "variable 'instance' is a EthereumData");
        }


        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Test]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }
        /// <summary>
        /// Test the property 'BlockNumber'
        /// </summary>
        [Test]
        public void BlockNumberTest()
        {
            // TODO unit test for the property 'BlockNumber'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'LocalHash'
        /// </summary>
        [Test]
        public void LocalHashTest()
        {
            // TODO unit test for the property 'LocalHash'
        }
        /// <summary>
        /// Test the property 'TransactionIndex'
        /// </summary>
        [Test]
        public void TransactionIndexTest()
        {
            // TODO unit test for the property 'TransactionIndex'
        }
        /// <summary>
        /// Test the property 'TxFrom'
        /// </summary>
        [Test]
        public void TxFromTest()
        {
            // TODO unit test for the property 'TxFrom'
        }
        /// <summary>
        /// Test the property 'TxTo'
        /// </summary>
        [Test]
        public void TxToTest()
        {
            // TODO unit test for the property 'TxTo'
        }

    }

}
