/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing GDPRRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GDPRRecipientTests
    {
        // TODO uncomment below to declare an instance variable for GDPRRecipient
        //private GDPRRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GDPRRecipient
            //instance = new GDPRRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GDPRRecipient
        /// </summary>
        [Test]
        public void GDPRRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GDPRRecipient
            //Assert.IsInstanceOfType<GDPRRecipient> (instance, "variable 'instance' is a GDPRRecipient");
        }


        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'LegalEntityType'
        /// </summary>
        [Test]
        public void LegalEntityTypeTest()
        {
            // TODO unit test for the property 'LegalEntityType'
        }
        /// <summary>
        /// Test the property 'LegalIdentifier'
        /// </summary>
        [Test]
        public void LegalIdentifierTest()
        {
            // TODO unit test for the property 'LegalIdentifier'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
