/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing LogResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogResponseTests
    {
        // TODO uncomment below to declare an instance variable for LogResponse
        //private LogResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogResponse
            //instance = new LogResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogResponse
        /// </summary>
        [Test]
        public void LogResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LogResponse
            //Assert.IsInstanceOfType<LogResponse> (instance, "variable 'instance' is a LogResponse");
        }


        /// <summary>
        /// Test the property 'LastKnownHash'
        /// </summary>
        [Test]
        public void LastKnownHashTest()
        {
            // TODO unit test for the property 'LastKnownHash'
        }
        /// <summary>
        /// Test the property 'LogEntryId'
        /// </summary>
        [Test]
        public void LogEntryIdTest()
        {
            // TODO unit test for the property 'LogEntryId'
        }
        /// <summary>
        /// Test the property 'StandaloneHash'
        /// </summary>
        [Test]
        public void StandaloneHashTest()
        {
            // TODO unit test for the property 'StandaloneHash'
        }

    }

}
