/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing MachineLearningSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MachineLearningSettingsTests
    {
        // TODO uncomment below to declare an instance variable for MachineLearningSettings
        //private MachineLearningSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MachineLearningSettings
            //instance = new MachineLearningSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MachineLearningSettings
        /// </summary>
        [Test]
        public void MachineLearningSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MachineLearningSettings
            //Assert.IsInstanceOfType<MachineLearningSettings> (instance, "variable 'instance' is a MachineLearningSettings");
        }


        /// <summary>
        /// Test the property 'AnomalyDetectionEnabled'
        /// </summary>
        [Test]
        public void AnomalyDetectionEnabledTest()
        {
            // TODO unit test for the property 'AnomalyDetectionEnabled'
        }
        /// <summary>
        /// Test the property 'AnomalyDetectionEnabledDate'
        /// </summary>
        [Test]
        public void AnomalyDetectionEnabledDateTest()
        {
            // TODO unit test for the property 'AnomalyDetectionEnabledDate'
        }
        /// <summary>
        /// Test the property 'IncludeEntityFields'
        /// </summary>
        [Test]
        public void IncludeEntityFieldsTest()
        {
            // TODO unit test for the property 'IncludeEntityFields'
        }
        /// <summary>
        /// Test the property 'TimestampField'
        /// </summary>
        [Test]
        public void TimestampFieldTest()
        {
            // TODO unit test for the property 'TimestampField'
        }

    }

}
