/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing ResolvedVerificationFailure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ResolvedVerificationFailureTests
    {
        // TODO uncomment below to declare an instance variable for ResolvedVerificationFailure
        //private ResolvedVerificationFailure instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ResolvedVerificationFailure
            //instance = new ResolvedVerificationFailure();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ResolvedVerificationFailure
        /// </summary>
        [Test]
        public void ResolvedVerificationFailureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResolvedVerificationFailure
            //Assert.IsInstanceOfType<ResolvedVerificationFailure> (instance, "variable 'instance' is a ResolvedVerificationFailure");
        }


        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'ResolvingUserId'
        /// </summary>
        [Test]
        public void ResolvingUserIdTest()
        {
            // TODO unit test for the property 'ResolvingUserId'
        }
        /// <summary>
        /// Test the property 'VerificationId'
        /// </summary>
        [Test]
        public void VerificationIdTest()
        {
            // TODO unit test for the property 'VerificationId'
        }

    }

}
