/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing SearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchRequestTests
    {
        // TODO uncomment below to declare an instance variable for SearchRequest
        //private SearchRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchRequest
            //instance = new SearchRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchRequest
        /// </summary>
        [Test]
        public void SearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchRequest
            //Assert.IsInstanceOfType<SearchRequest> (instance, "variable 'instance' is a SearchRequest");
        }


        /// <summary>
        /// Test the property 'ApplicationIds'
        /// </summary>
        [Test]
        public void ApplicationIdsTest()
        {
            // TODO unit test for the property 'ApplicationIds'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Test]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Test]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'TimestampField'
        /// </summary>
        [Test]
        public void TimestampFieldTest()
        {
            // TODO unit test for the property 'TimestampField'
        }

    }

}
