/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing UpdateApplicationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UpdateApplicationRequestTests
    {
        // TODO uncomment below to declare an instance variable for UpdateApplicationRequest
        //private UpdateApplicationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateApplicationRequest
            //instance = new UpdateApplicationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateApplicationRequest
        /// </summary>
        [Test]
        public void UpdateApplicationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateApplicationRequest
            //Assert.IsInstanceOfType<UpdateApplicationRequest> (instance, "variable 'instance' is a UpdateApplicationRequest");
        }


        /// <summary>
        /// Test the property 'ContainsPersonalData'
        /// </summary>
        [Test]
        public void ContainsPersonalDataTest()
        {
            // TODO unit test for the property 'ContainsPersonalData'
        }
        /// <summary>
        /// Test the property 'DetailsTransformationScript'
        /// </summary>
        [Test]
        public void DetailsTransformationScriptTest()
        {
            // TODO unit test for the property 'DetailsTransformationScript'
        }
        /// <summary>
        /// Test the property 'DisplayedDetailsFields'
        /// </summary>
        [Test]
        public void DisplayedDetailsFieldsTest()
        {
            // TODO unit test for the property 'DisplayedDetailsFields'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IpWhiteList'
        /// </summary>
        [Test]
        public void IpWhiteListTest()
        {
            // TODO unit test for the property 'IpWhiteList'
        }
        /// <summary>
        /// Test the property 'LatestHashRecipientEmails'
        /// </summary>
        [Test]
        public void LatestHashRecipientEmailsTest()
        {
            // TODO unit test for the property 'LatestHashRecipientEmails'
        }
        /// <summary>
        /// Test the property 'LogLevelErrorReportRecipientEmails'
        /// </summary>
        [Test]
        public void LogLevelErrorReportRecipientEmailsTest()
        {
            // TODO unit test for the property 'LogLevelErrorReportRecipientEmails'
        }
        /// <summary>
        /// Test the property 'LogLevelRegexes'
        /// </summary>
        [Test]
        public void LogLevelRegexesTest()
        {
            // TODO unit test for the property 'LogLevelRegexes'
        }
        /// <summary>
        /// Test the property 'MetadataExtractionPaths'
        /// </summary>
        [Test]
        public void MetadataExtractionPathsTest()
        {
            // TODO unit test for the property 'MetadataExtractionPaths'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OpenDataAnonymizationRegexes'
        /// </summary>
        [Test]
        public void OpenDataAnonymizationRegexesTest()
        {
            // TODO unit test for the property 'OpenDataAnonymizationRegexes'
        }
        /// <summary>
        /// Test the property 'OpenDataAnonymizeBodyFields'
        /// </summary>
        [Test]
        public void OpenDataAnonymizeBodyFieldsTest()
        {
            // TODO unit test for the property 'OpenDataAnonymizeBodyFields'
        }
        /// <summary>
        /// Test the property 'OpenDataEnabled'
        /// </summary>
        [Test]
        public void OpenDataEnabledTest()
        {
            // TODO unit test for the property 'OpenDataEnabled'
        }
        /// <summary>
        /// Test the property 'OpenDataWhitelistRegexes'
        /// </summary>
        [Test]
        public void OpenDataWhitelistRegexesTest()
        {
            // TODO unit test for the property 'OpenDataWhitelistRegexes'
        }
        /// <summary>
        /// Test the property 'PartialVerificationPeriodMinutes'
        /// </summary>
        [Test]
        public void PartialVerificationPeriodMinutesTest()
        {
            // TODO unit test for the property 'PartialVerificationPeriodMinutes'
        }
        /// <summary>
        /// Test the property 'RetentionMonths'
        /// </summary>
        [Test]
        public void RetentionMonthsTest()
        {
            // TODO unit test for the property 'RetentionMonths'
        }
        /// <summary>
        /// Test the property 'SignatureVerificationPublicKeys'
        /// </summary>
        [Test]
        public void SignatureVerificationPublicKeysTest()
        {
            // TODO unit test for the property 'SignatureVerificationPublicKeys'
        }
        /// <summary>
        /// Test the property 'StoreHashesInEthereum'
        /// </summary>
        [Test]
        public void StoreHashesInEthereumTest()
        {
            // TODO unit test for the property 'StoreHashesInEthereum'
        }
        /// <summary>
        /// Test the property 'VerificationFailureReportRecipientEmails'
        /// </summary>
        [Test]
        public void VerificationFailureReportRecipientEmailsTest()
        {
            // TODO unit test for the property 'VerificationFailureReportRecipientEmails'
        }
        /// <summary>
        /// Test the property 'VerificationPeriodMinutes'
        /// </summary>
        [Test]
        public void VerificationPeriodMinutesTest()
        {
            // TODO unit test for the property 'VerificationPeriodMinutes'
        }
        /// <summary>
        /// Test the property 'WarnLevel'
        /// </summary>
        [Test]
        public void WarnLevelTest()
        {
            // TODO unit test for the property 'WarnLevel'
        }

    }

}
