/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing UserRegistrationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserRegistrationRequestTests
    {
        // TODO uncomment below to declare an instance variable for UserRegistrationRequest
        //private UserRegistrationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserRegistrationRequest
            //instance = new UserRegistrationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserRegistrationRequest
        /// </summary>
        [Test]
        public void UserRegistrationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserRegistrationRequest
            //Assert.IsInstanceOfType<UserRegistrationRequest> (instance, "variable 'instance' is a UserRegistrationRequest");
        }


        /// <summary>
        /// Test the property 'AllowedApplicationIds'
        /// </summary>
        [Test]
        public void AllowedApplicationIdsTest()
        {
            // TODO unit test for the property 'AllowedApplicationIds'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'AwsCustomerId'
        /// </summary>
        [Test]
        public void AwsCustomerIdTest()
        {
            // TODO unit test for the property 'AwsCustomerId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ExpirationDate'
        /// </summary>
        [Test]
        public void ExpirationDateTest()
        {
            // TODO unit test for the property 'ExpirationDate'
        }
        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Test]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }
        /// <summary>
        /// Test the property 'Names'
        /// </summary>
        [Test]
        public void NamesTest()
        {
            // TODO unit test for the property 'Names'
        }
        /// <summary>
        /// Test the property 'OrganizationName'
        /// </summary>
        [Test]
        public void OrganizationNameTest()
        {
            // TODO unit test for the property 'OrganizationName'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'ServerName'
        /// </summary>
        [Test]
        public void ServerNameTest()
        {
            // TODO unit test for the property 'ServerName'
        }
        /// <summary>
        /// Test the property 'SubscriptionPlanCode'
        /// </summary>
        [Test]
        public void SubscriptionPlanCodeTest()
        {
            // TODO unit test for the property 'SubscriptionPlanCode'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
