/* 
 * LogSentinel RESTful API
 *
 * Read more at https://docs.logsentinel.com/en/latest/index.html
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using LogSentinel.Client.Api;
using LogSentinel.Client.Model;
using LogSentinel.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace LogSentinel.Client.Test
{
    /// <summary>
    ///  Class for testing Verification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VerificationTests
    {
        // TODO uncomment below to declare an instance variable for Verification
        //private Verification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Verification
            //instance = new Verification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Verification
        /// </summary>
        [Test]
        public void VerificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Verification
            //Assert.IsInstanceOfType<Verification> (instance, "variable 'instance' is a Verification");
        }


        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Test]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'AttemptedHash'
        /// </summary>
        [Test]
        public void AttemptedHashTest()
        {
            // TODO unit test for the property 'AttemptedHash'
        }
        /// <summary>
        /// Test the property 'AuditLogEntryId'
        /// </summary>
        [Test]
        public void AuditLogEntryIdTest()
        {
            // TODO unit test for the property 'AuditLogEntryId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Failure'
        /// </summary>
        [Test]
        public void FailureTest()
        {
            // TODO unit test for the property 'Failure'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
