/* 
 * LogSentinel RESTful API
 *
 * Read more at https://app.logsentinel.com/docs
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using LogSentinel.Client;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IHashControllerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Compute the hash of a request for auth actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        string GetHashableContentForAuthActionUsingPOST1 (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for auth actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GetHashableContentForAuthActionUsingPOST1WithHttpInfo (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null);
        /// <summary>
        /// Compute the hash of a request for standard actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        string GetHashableContentForStandardActionUsingPOST1 (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for standard actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GetHashableContentForStandardActionUsingPOST1WithHttpInfo (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);
        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>string</returns>
        string GetHashableContentSimpleUsingPOST1 (string details, string applicationId, string signature = null, string auditLogEntryType = null);

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GetHashableContentSimpleUsingPOST1WithHttpInfo (string details, string applicationId, string signature = null, string auditLogEntryType = null);
        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        string GetHashableContentUsingPOST1 (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> GetHashableContentUsingPOST1WithHttpInfo (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Compute the hash of a request for auth actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GetHashableContentForAuthActionUsingPOST1Async (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for auth actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentForAuthActionUsingPOST1AsyncWithHttpInfo (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null);
        /// <summary>
        /// Compute the hash of a request for standard actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GetHashableContentForStandardActionUsingPOST1Async (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for standard actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentForStandardActionUsingPOST1AsyncWithHttpInfo (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);
        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GetHashableContentSimpleUsingPOST1Async (string details, string applicationId, string signature = null, string auditLogEntryType = null);

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentSimpleUsingPOST1AsyncWithHttpInfo (string details, string applicationId, string signature = null, string auditLogEntryType = null);
        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> GetHashableContentUsingPOST1Async (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentUsingPOST1AsyncWithHttpInfo (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class HashControllerApi : IHashControllerApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        private ApiClient apiClient;
        private BodySerializer bodySerializer;
        private BodySigner bodySigner;
        private String contentType;

        /// <summary>
        /// Initializes a new instance of the <see cref="HashControllerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public HashControllerApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        public HashControllerApi(ApiClient apiClient, BodySerializer bodySerializer, BodySigner signer, String contentType)
        {
            this.apiClient = apiClient;
            this.bodySerializer = bodySerializer;
            this.bodySigner = signer;
            this.contentType = contentType;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HashControllerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public HashControllerApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Compute the hash of a request for auth actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        public string GetHashableContentForAuthActionUsingPOST1 (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = GetHashableContentForAuthActionUsingPOST1WithHttpInfo(actorId, authAction, details, applicationId, signedLoginChallenge, userPublicKey, signature, actorDisplayName, actorRoles);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Compute the hash of a request for auth actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GetHashableContentForAuthActionUsingPOST1WithHttpInfo (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'authAction' is set
            if (authAction == null)
                throw new ApiException(400, "Missing required parameter 'authAction' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/auth/{authAction}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (authAction != null) localVarPathParams.Add("authAction", Configuration.ApiClient.ParameterToString(authAction)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (signedLoginChallenge != null) localVarHeaderParams.Add("Signed-Login-Challenge", Configuration.ApiClient.ParameterToString(signedLoginChallenge)); // header parameter
            if (userPublicKey != null) localVarHeaderParams.Add("User-Public-Key", Configuration.ApiClient.ParameterToString(userPublicKey)); // header parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentForAuthActionUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request for auth actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GetHashableContentForAuthActionUsingPOST1Async (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = await GetHashableContentForAuthActionUsingPOST1AsyncWithHttpInfo(actorId, authAction, details, applicationId, signedLoginChallenge, userPublicKey, signature, actorDisplayName, actorRoles);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Compute the hash of a request for auth actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="authAction">Specific action related to user authentication</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signedLoginChallenge">Signed-Login-Challenge (optional)</param>
        /// <param name="userPublicKey">User-Public-Key (optional)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentForAuthActionUsingPOST1AsyncWithHttpInfo (string actorId, string authAction, string details, string applicationId, string signedLoginChallenge = null, string userPublicKey = null, string signature = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'authAction' is set
            if (authAction == null)
                throw new ApiException(400, "Missing required parameter 'authAction' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentForAuthActionUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/auth/{authAction}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (authAction != null) localVarPathParams.Add("authAction", Configuration.ApiClient.ParameterToString(authAction)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (signedLoginChallenge != null) localVarHeaderParams.Add("Signed-Login-Challenge", Configuration.ApiClient.ParameterToString(signedLoginChallenge)); // header parameter
            if (userPublicKey != null) localVarHeaderParams.Add("User-Public-Key", Configuration.ApiClient.ParameterToString(userPublicKey)); // header parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentForAuthActionUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request for standard actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        public string GetHashableContentForStandardActionUsingPOST1 (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = GetHashableContentForStandardActionUsingPOST1WithHttpInfo(actorId, action, entityType, entityId, details, applicationId, signature, auditLogEntryType, actorDisplayName, actorRoles);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Compute the hash of a request for standard actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GetHashableContentForStandardActionUsingPOST1WithHttpInfo (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'entityType' is set
            if (entityType == null)
                throw new ApiException(400, "Missing required parameter 'entityType' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'entityId' is set
            if (entityId == null)
                throw new ApiException(400, "Missing required parameter 'entityId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/{action}/{entityType}/{entityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (action != null) localVarPathParams.Add("action", Configuration.ApiClient.ParameterToString(action)); // path parameter
            if (entityType != null) localVarPathParams.Add("entityType", Configuration.ApiClient.ParameterToString(entityType)); // path parameter
            if (entityId != null) localVarPathParams.Add("entityId", Configuration.ApiClient.ParameterToString(entityId)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentForStandardActionUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request for standard actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GetHashableContentForStandardActionUsingPOST1Async (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = await GetHashableContentForStandardActionUsingPOST1AsyncWithHttpInfo(actorId, action, entityType, entityId, details, applicationId, signature, auditLogEntryType, actorDisplayName, actorRoles);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Compute the hash of a request for standard actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="entityType">When the event is about a particular model entity, you can set its type here</param>
        /// <param name="entityId">When the event is about a particular model entity, you can set its ID here</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentForStandardActionUsingPOST1AsyncWithHttpInfo (string actorId, string action, string entityType, string entityId, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'entityType' is set
            if (entityType == null)
                throw new ApiException(400, "Missing required parameter 'entityType' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'entityId' is set
            if (entityId == null)
                throw new ApiException(400, "Missing required parameter 'entityId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentForStandardActionUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/{action}/{entityType}/{entityId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (action != null) localVarPathParams.Add("action", Configuration.ApiClient.ParameterToString(action)); // path parameter
            if (entityType != null) localVarPathParams.Add("entityType", Configuration.ApiClient.ParameterToString(entityType)); // path parameter
            if (entityId != null) localVarPathParams.Add("entityId", Configuration.ApiClient.ParameterToString(entityId)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentForStandardActionUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>string</returns>
        public string GetHashableContentSimpleUsingPOST1 (string details, string applicationId, string signature = null, string auditLogEntryType = null)
        {
             ApiResponse<string> localVarResponse = GetHashableContentSimpleUsingPOST1WithHttpInfo(details, applicationId, signature, auditLogEntryType);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GetHashableContentSimpleUsingPOST1WithHttpInfo (string details, string applicationId, string signature = null, string auditLogEntryType = null)
        {
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentSimpleUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentSimpleUsingPOST1");

            var localVarPath = "/api/getHashableContent";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentSimpleUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GetHashableContentSimpleUsingPOST1Async (string details, string applicationId, string signature = null, string auditLogEntryType = null)
        {
             ApiResponse<string> localVarResponse = await GetHashableContentSimpleUsingPOST1AsyncWithHttpInfo(details, applicationId, signature, auditLogEntryType);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Compute the hash of a request without any additional metadata (including encrypted request bodies) 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentSimpleUsingPOST1AsyncWithHttpInfo (string details, string applicationId, string signature = null, string auditLogEntryType = null)
        {
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentSimpleUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentSimpleUsingPOST1");

            var localVarPath = "/api/getHashableContent";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml",
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentSimpleUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>string</returns>
        public string GetHashableContentUsingPOST1 (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = GetHashableContentUsingPOST1WithHttpInfo(actorId, action, details, applicationId, signature, auditLogEntryType, actorDisplayName, actorRoles);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > GetHashableContentUsingPOST1WithHttpInfo (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/{action}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (action != null) localVarPathParams.Add("action", Configuration.ApiClient.ParameterToString(action)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> GetHashableContentUsingPOST1Async (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
             ApiResponse<string> localVarResponse = await GetHashableContentUsingPOST1AsyncWithHttpInfo(actorId, action, details, applicationId, signature, auditLogEntryType, actorDisplayName, actorRoles);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Compute the hash of a request for simple (minimial metadata) actions 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="actorId">ID of the actor performing the action being logged</param>
        /// <param name="action">The name of the action being logged</param>
        /// <param name="details">Any details in any format about the event that you want to store in the log</param>
        /// <param name="applicationId">Application ID, identifying a target application (obtained from the API credentials page)</param>
        /// <param name="signature">Base64-encoded digital signature on the entry details (the request body) (optional)</param>
        /// <param name="auditLogEntryType">The type of the event (optional, default to BUSINESS_LOGIC_ENTRY)</param>
        /// <param name="actorDisplayName">Display name of the actor (e.g. a name, in case ID is not human-readable) (optional)</param>
        /// <param name="actorRoles">The roles of the actor (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> GetHashableContentUsingPOST1AsyncWithHttpInfo (string actorId, string action, string details, string applicationId, string signature = null, string auditLogEntryType = null, string actorDisplayName = null, List<string> actorRoles = null)
        {
            // verify the required parameter 'actorId' is set
            if (actorId == null)
                throw new ApiException(400, "Missing required parameter 'actorId' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'action' is set
            if (action == null)
                throw new ApiException(400, "Missing required parameter 'action' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'details' is set
            if (details == null)
                throw new ApiException(400, "Missing required parameter 'details' when calling HashControllerApi->GetHashableContentUsingPOST1");
            // verify the required parameter 'applicationId' is set
            if (applicationId == null)
                throw new ApiException(400, "Missing required parameter 'applicationId' when calling HashControllerApi->GetHashableContentUsingPOST1");

            var localVarPath = "/api/getHashableContent/{actorId}/{action}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "*/*"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "*/*"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (actorId != null) localVarPathParams.Add("actorId", Configuration.ApiClient.ParameterToString(actorId)); // path parameter
            if (action != null) localVarPathParams.Add("action", Configuration.ApiClient.ParameterToString(action)); // path parameter
            if (actorDisplayName != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "actorDisplayName", actorDisplayName)); // query parameter
            if (actorRoles != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("multi", "actorRoles", actorRoles)); // query parameter
            if (applicationId != null) localVarHeaderParams.Add("Application-Id", Configuration.ApiClient.ParameterToString(applicationId)); // header parameter
            if (signature != null) localVarHeaderParams.Add("Signature", Configuration.ApiClient.ParameterToString(signature)); // header parameter
            if (auditLogEntryType != null) localVarHeaderParams.Add("Audit-Log-Entry-Type", Configuration.ApiClient.ParameterToString(auditLogEntryType)); // header parameter
            if (details != null && details.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(details); // http body (model) parameter
            }
            else
            {
                localVarPostBody = details; // byte array
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(Configuration.Username) || !String.IsNullOrEmpty(Configuration.Password))
            {
                localVarHeaderParams["Authorization"] = "Basic " + ApiClient.Base64Encode(Configuration.Username + ":" + Configuration.Password);
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetHashableContentUsingPOST1", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string) Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
